name: butter_api_commons
description: Common API Utilities for butter systems
version: 2.6.0
publish_to: none
homepage: https://applybutter.com
repository: https://github.com/kbaylosis/butter/tree/master/packages/api_commons

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  butter_commons:
    git: 
      url: https://github.com/rodJam/butter_update.git
      ref: temp
      path: "packages/api_commons"
  collection: ^1.18.0
  conduit: ^5.1.3
  conduit_common: ^5.1.3
  conduit_core: ^5.1.3
  conduit_open_api: ^5.1.3
  conduit_postgresql: ^5.1.3
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  conduit_test: ^5.0.0
  faker: ^2.1.0
  lints: ^2.0.0
  test: ^1.25.2
